In [1]:
import pandas as pd
import numpy
import matplotlib as plt
import pickle as pkl
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("data/comic_characters.csv")
pd.DataFrame(df)

,Id,Name,Identity,Alignment,Eyes,Hair,Sex,Alive,Appearances,First_appeared,Planet,Universe
0,0,Dave Finn,Secret,Good,Blue,Black,Male,Yes,1,"2002, July",Earth-616,Marvel
1,1,Katherine Power,Secret,Good,Blue,Red,Female,Yes,106,"1984, August",Earth-616,Marvel
2,2,John Malone,Secret,Bad,Blue,White,Male,Yes,15,"1985, January",New Earth,DC
3,3,"Samuel Bradley, Jr.",Public,Bad,Brown,Brown,Male,No,19,"2004, March",New Earth,DC
4,4,Hope Taya,Public,Bad,Brown,Black,Female,Yes,28,"1999, December",New Earth,DC
...,...,...,...,...,...,...,...,...,...,...,...,...
21139,21139,Winslow Schott,Public,Bad,Blue,Brown,Male,Yes,74,"1943, September",New Earth,DC
21140,21140,Jim Morita,Secret,Bad,Brown,Black,Male,Yes,4,"1967, January",Earth-616,Marvel
21141,21141,Janet Grant,Public,Good,Brown,Black,Female,Yes,1,"2007, December",Earth-616,Marvel
21142,21142,Miya Shimada,Secret,Good,Brown,Black,Female,Yes,46,"1984, May",New Earth,DC
21143,21143,Loria,Secret,Good,Green,Black,Female,No,6,"1994, December",New Earth,DC

In [3]:
eye = {"Blue": 0, "Brown": 1, "Green": 2, "Black": 3, "White": 4, "Variable": 5, "Hazel": 6, "Yellow": 7, "Red": 8, "Grey": 9, "Purple": 10, "Orange": 11, "Aubrun": 12, "Photocellular": 13, "Silver": 14}
df["Eyes"] = df["Eyes"].map(eye)

hair = {"Black": 0, "Red": 1, "White": 2, "Brown": 3, "Blond": 4, "No": 5, "Bald": 6, "Green": 7, "Orange": 8, "Variable": 9, "Grey": 10, "Blue": 11, "Auburn": 12, "Silver": 13, "Yellow": 14}
df["Hair"] = df["Hair"].map(hair)

i = {"Secret": 0, "Public": 1}
df["Identity"] = df["Identity"].map(i)

al = {"Good": 0, "Bad": 1}
df["Alignment"] = df["Alignment"].map(al)

sex = {"Male": 0, "Female": 1}
df["Sex"] = df["Sex"].map(sex)

alive = {"Yes": 0, "No": 1}
df["Alive"] = df["Alive"].map(alive)

Uni = {"DC": 0, "Marvel": 1}
df["Universe"] = df["Universe"].map(Uni)

features = ["Eyes", "Hair", "Identity", "Alignment", "Sex", "Alive", "Universe"]

X = df[features]
y = df["Name"]

In [4]:
dtree = DecisionTreeClassifier()
dtree.fit(X, y)

model_filename = 'MarvelDCName.pkl'
pkl.dump(dtree, open(model_filename,'wb'))

In [8]:
model = pkl.load(open('MarvelDCName.pkl','rb'))
print(model.predict([[13, 1, 1, 1, 0, 0, 1]]))

['Behemoth']

/home/victorgd/Documents/MLKaggle/venv/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(